on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  ai_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install AI review
        run: |
          pip install git+https://github.com/UtkarshRanjanSurya/ai-review.git

      - name: Debug key
        run: |
          echo "Key length: ${#GEMINI_API_KEY}"
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Run AI Review
        env:
          LLM__PROVIDER: "GEMINI"
          LLM__META__MODEL: "gemini-1.5-flash"
          LLM__HTTP_CLIENT__API_URL: "https://generativelanguage.googleapis.com"
          LLM__HTTP_CLIENT__API_TOKEN: ${{ secrets.GEMINI_API_KEY }}


          # GitHub config
          VCS__PROVIDER: "GITHUB"
          VCS__PIPELINE__OWNER: "Utkarsh89890"
          VCS__PIPELINE__REPO: "ai-review-test"
          VCS__PIPELINE__PULL_NUMBER: ${{ github.event.pull_request.number }}
          VCS__HTTP_CLIENT__API_URL: "https://api.github.com"
          VCS__HTTP_CLIENT__API_TOKEN: ${{ secrets.GH_PAT }}

        run: |
          ai-review run-inline
          ai-review run-context
          ai-review run-summary
